version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd frontend
      - npm install
      - npm run deploy
      - cd ../backend
      - npm install
      - npm run deploy
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - backend/deploy.zip